package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * Batchfilepath generated by hbm2java
 */
public class Batchfilepath implements java.io.Serializable {

	private Integer batchfilepathid;
	private Server server;
	private String batchfilepath;

	public Batchfilepath() {
	}

	public Batchfilepath(Server server, String batchfilepath) {
		this.server = server;
		this.batchfilepath = batchfilepath;
	}

	public Integer getBatchfilepathid() {
		return this.batchfilepathid;
	}

	public void setBatchfilepathid(Integer batchfilepathid) {
		this.batchfilepathid = batchfilepathid;
	}

	public Server getServer() {
		return this.server;
	}

	public void setServer(Server server) {
		this.server = server;
	}

	public String getBatchfilepath() {
		return this.batchfilepath;
	}

	public void setBatchfilepath(String batchfilepath) {
		this.batchfilepath = batchfilepath;
	}

}
