package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Browser generated by hbm2java
 */
public class Browser implements java.io.Serializable {

	private Integer browserid;
	private Server server;
	private String browsername;
	private String browserpath;
	private Set selwowschedulers = new HashSet(0);

	public Browser() {
	}

	public Browser(String browsername) {
		this.browsername = browsername;
	}

	public Browser(Server server, String browsername, String browserpath,
			Set selwowschedulers) {
		this.server = server;
		this.browsername = browsername;
		this.browserpath = browserpath;
		this.selwowschedulers = selwowschedulers;
	}

	public Integer getBrowserid() {
		return this.browserid;
	}

	public void setBrowserid(Integer browserid) {
		this.browserid = browserid;
	}

	public Server getServer() {
		return this.server;
	}

	public void setServer(Server server) {
		this.server = server;
	}

	public String getBrowsername() {
		return this.browsername;
	}

	public void setBrowsername(String browsername) {
		this.browsername = browsername;
	}

	public String getBrowserpath() {
		return this.browserpath;
	}

	public void setBrowserpath(String browserpath) {
		this.browserpath = browserpath;
	}

	public Set getSelwowschedulers() {
		return this.selwowschedulers;
	}

	public void setSelwowschedulers(Set selwowschedulers) {
		this.selwowschedulers = selwowschedulers;
	}

}
