package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * BuildResults generated by hbm2java
 */
public class BuildResults implements java.io.Serializable {

	private Integer buildresultid;
	private Suite suite;
	private String buildresult;

	public BuildResults() {
	}

	public BuildResults(Suite suite, String buildresult) {
		this.suite = suite;
		this.buildresult = buildresult;
	}

	public Integer getBuildresultid() {
		return this.buildresultid;
	}

	public void setBuildresultid(Integer buildresultid) {
		this.buildresultid = buildresultid;
	}

	public Suite getSuite() {
		return this.suite;
	}

	public void setSuite(Suite suite) {
		this.suite = suite;
	}

	public String getBuildresult() {
		return this.buildresult;
	}

	public void setBuildresult(String buildresult) {
		this.buildresult = buildresult;
	}

}
