package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Environment generated by hbm2java
 */
public class Environment implements java.io.Serializable {

	private Integer environmentid;
	private String environmentname;
	private String ipaddress;
	private Set selwowschedulers = new HashSet(0);

	public Environment() {
	}

	public Environment(String environmentname, String ipaddress,
			Set selwowschedulers) {
		this.environmentname = environmentname;
		this.ipaddress = ipaddress;
		this.selwowschedulers = selwowschedulers;
	}

	public Integer getEnvironmentid() {
		return this.environmentid;
	}

	public void setEnvironmentid(Integer environmentid) {
		this.environmentid = environmentid;
	}

	public String getEnvironmentname() {
		return this.environmentname;
	}

	public void setEnvironmentname(String environmentname) {
		this.environmentname = environmentname;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public Set getSelwowschedulers() {
		return this.selwowschedulers;
	}

	public void setSelwowschedulers(Set selwowschedulers) {
		this.selwowschedulers = selwowschedulers;
	}

}
