package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Outputfile generated by hbm2java
 */
public class Outputfile implements java.io.Serializable {

	private Integer outputfileid;
	private String outputfile;
	private Set selwowschedulers = new HashSet(0);

	public Outputfile() {
	}

	public Outputfile(String outputfile, Set selwowschedulers) {
		this.outputfile = outputfile;
		this.selwowschedulers = selwowschedulers;
	}

	public Integer getOutputfileid() {
		return this.outputfileid;
	}

	public void setOutputfileid(Integer outputfileid) {
		this.outputfileid = outputfileid;
	}

	public String getOutputfile() {
		return this.outputfile;
	}

	public void setOutputfile(String outputfile) {
		this.outputfile = outputfile;
	}

	public Set getSelwowschedulers() {
		return this.selwowschedulers;
	}

	public void setSelwowschedulers(Set selwowschedulers) {
		this.selwowschedulers = selwowschedulers;
	}

}
