package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * Scheduledjobs generated by hbm2java
 */
public class Scheduledjobs implements java.io.Serializable {

	private Integer schedulejobid;
	private Selwowscheduler selwowscheduler;
	private String jobdescriptionkey;
	private String triggerkey;
	private int jobstatusid;
	private Integer goodToGo;
	private Integer isSingle;
	private int port;
	private int processId;

	public Scheduledjobs() {
	}

	public Scheduledjobs(int jobstatusid, int port, int processId) {
		this.jobstatusid = jobstatusid;
		this.port = port;
		this.processId = processId;
	}

	public Scheduledjobs(Selwowscheduler selwowscheduler,
			String jobdescriptionkey, String triggerkey, int jobstatusid,
			Integer goodToGo, Integer isSingle, int port, int processId) {
		this.selwowscheduler = selwowscheduler;
		this.jobdescriptionkey = jobdescriptionkey;
		this.triggerkey = triggerkey;
		this.jobstatusid = jobstatusid;
		this.goodToGo = goodToGo;
		this.isSingle = isSingle;
		this.port = port;
		this.processId = processId;
	}

	public Integer getSchedulejobid() {
		return this.schedulejobid;
	}

	public void setSchedulejobid(Integer schedulejobid) {
		this.schedulejobid = schedulejobid;
	}

	public Selwowscheduler getSelwowscheduler() {
		return this.selwowscheduler;
	}

	public void setSelwowscheduler(Selwowscheduler selwowscheduler) {
		this.selwowscheduler = selwowscheduler;
	}

	public String getJobdescriptionkey() {
		return this.jobdescriptionkey;
	}

	public void setJobdescriptionkey(String jobdescriptionkey) {
		this.jobdescriptionkey = jobdescriptionkey;
	}

	public String getTriggerkey() {
		return this.triggerkey;
	}

	public void setTriggerkey(String triggerkey) {
		this.triggerkey = triggerkey;
	}

	public int getJobstatusid() {
		return this.jobstatusid;
	}

	public void setJobstatusid(int jobstatusid) {
		this.jobstatusid = jobstatusid;
	}

	public Integer getGoodToGo() {
		return this.goodToGo;
	}

	public void setGoodToGo(Integer goodToGo) {
		this.goodToGo = goodToGo;
	}

	public Integer getIsSingle() {
		return this.isSingle;
	}

	public void setIsSingle(Integer isSingle) {
		this.isSingle = isSingle;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public int getProcessId() {
		return this.processId;
	}

	public void setProcessId(int processId) {
		this.processId = processId;
	}

}
