package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * Scheduledjobstatus generated by hbm2java
 */
public class Scheduledjobstatus implements java.io.Serializable {

	private Integer jobstatusid;
	private String jobstatusname;

	public Scheduledjobstatus() {
	}

	public Scheduledjobstatus(String jobstatusname) {
		this.jobstatusname = jobstatusname;
	}

	public Integer getJobstatusid() {
		return this.jobstatusid;
	}

	public void setJobstatusid(Integer jobstatusid) {
		this.jobstatusid = jobstatusid;
	}

	public String getJobstatusname() {
		return this.jobstatusname;
	}

	public void setJobstatusname(String jobstatusname) {
		this.jobstatusname = jobstatusname;
	}

}
