package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * Scheduledgroups generated by hbm2java
 */
public class Scheduledgroups implements java.io.Serializable {

	private Integer scheduledgroupid;
	private int schedulerid;
	private int groupid;

	public Scheduledgroups() {
	}

	public Scheduledgroups(int schedulerid, int groupid) {
		this.schedulerid = schedulerid;
		this.groupid = groupid;
	}

	public Integer getScheduledgroupid() {
		return this.scheduledgroupid;
	}

	public void setScheduledgroupid(Integer scheduledgroupid) {
		this.scheduledgroupid = scheduledgroupid;
	}

	public int getSchedulerid() {
		return this.schedulerid;
	}

	public void setSchedulerid(int schedulerid) {
		this.schedulerid = schedulerid;
	}

	public int getGroupid() {
		return this.groupid;
	}

	public void setGroupid(int groupid) {
		this.groupid = groupid;
	}

}
