package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Selwowusers generated by hbm2java
 */
public class Selwowusers implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String useremail;
	private Set selwowschedulers = new HashSet(0);

	public Selwowusers() {
	}

	public Selwowusers(String username, String useremail, Set selwowschedulers) {
		this.username = username;
		this.useremail = useremail;
		this.selwowschedulers = selwowschedulers;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUseremail() {
		return this.useremail;
	}

	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	public Set getSelwowschedulers() {
		return this.selwowschedulers;
	}

	public void setSelwowschedulers(Set selwowschedulers) {
		this.selwowschedulers = selwowschedulers;
	}

}
