package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Server generated by hbm2java
 */
public class Server implements java.io.Serializable {

	private Integer serverid;
	private Operatingsystem operatingsystem;
	private String servername;
	private String serverip;
	private int serverport;
	private int isSelwowschedulerServer;
	private int session;
	private Set selwowschedulers = new HashSet(0);
	private Set batchfilepaths = new HashSet(0);
	private Set xmlfilepaths = new HashSet(0);
	private Set browsers = new HashSet(0);

	public Server() {
	}

	public Server(Operatingsystem operatingsystem, String servername,
			String serverip, int serverport, int isSelwowschedulerServer,
			int session) {
		this.operatingsystem = operatingsystem;
		this.servername = servername;
		this.serverip = serverip;
		this.serverport = serverport;
		this.isSelwowschedulerServer = isSelwowschedulerServer;
		this.session = session;
	}

	public Server(Operatingsystem operatingsystem, String servername,
			String serverip, int serverport, int isSelwowschedulerServer,
			int session, Set selwowschedulers, Set batchfilepaths,
			Set xmlfilepaths, Set browsers) {
		this.operatingsystem = operatingsystem;
		this.servername = servername;
		this.serverip = serverip;
		this.serverport = serverport;
		this.isSelwowschedulerServer = isSelwowschedulerServer;
		this.session = session;
		this.selwowschedulers = selwowschedulers;
		this.batchfilepaths = batchfilepaths;
		this.xmlfilepaths = xmlfilepaths;
		this.browsers = browsers;
	}

	public Integer getServerid() {
		return this.serverid;
	}

	public void setServerid(Integer serverid) {
		this.serverid = serverid;
	}

	public Operatingsystem getOperatingsystem() {
		return this.operatingsystem;
	}

	public void setOperatingsystem(Operatingsystem operatingsystem) {
		this.operatingsystem = operatingsystem;
	}

	public String getServername() {
		return this.servername;
	}

	public void setServername(String servername) {
		this.servername = servername;
	}

	public String getServerip() {
		return this.serverip;
	}

	public void setServerip(String serverip) {
		this.serverip = serverip;
	}

	public int getServerport() {
		return this.serverport;
	}

	public void setServerport(int serverport) {
		this.serverport = serverport;
	}

	public int getIsSelwowschedulerServer() {
		return this.isSelwowschedulerServer;
	}

	public void setIsSelwowschedulerServer(int isSelwowschedulerServer) {
		this.isSelwowschedulerServer = isSelwowschedulerServer;
	}

	public int getSession() {
		return this.session;
	}

	public void setSession(int session) {
		this.session = session;
	}

	public Set getSelwowschedulers() {
		return this.selwowschedulers;
	}

	public void setSelwowschedulers(Set selwowschedulers) {
		this.selwowschedulers = selwowschedulers;
	}

	public Set getBatchfilepaths() {
		return this.batchfilepaths;
	}

	public void setBatchfilepaths(Set batchfilepaths) {
		this.batchfilepaths = batchfilepaths;
	}

	public Set getXmlfilepaths() {
		return this.xmlfilepaths;
	}

	public void setXmlfilepaths(Set xmlfilepaths) {
		this.xmlfilepaths = xmlfilepaths;
	}

	public Set getBrowsers() {
		return this.browsers;
	}

	public void setBrowsers(Set browsers) {
		this.browsers = browsers;
	}

}
