package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Testcase generated by hbm2java
 */
public class Testcase implements java.io.Serializable {

	private Integer testcaseid;
	private Grouping grouping;
	private String testcasename;
	private String testcasedescription;
	private int tfsid;
	private int status;
	private Set testcaseresultses = new HashSet(0);

	public Testcase() {
	}

	public Testcase(Grouping grouping, String testcasename, int tfsid,
			int status) {
		this.grouping = grouping;
		this.testcasename = testcasename;
		this.tfsid = tfsid;
		this.status = status;
	}

	public Testcase(Grouping grouping, String testcasename,
			String testcasedescription, int tfsid, int status,
			Set testcaseresultses) {
		this.grouping = grouping;
		this.testcasename = testcasename;
		this.testcasedescription = testcasedescription;
		this.tfsid = tfsid;
		this.status = status;
		this.testcaseresultses = testcaseresultses;
	}

	public Integer getTestcaseid() {
		return this.testcaseid;
	}

	public void setTestcaseid(Integer testcaseid) {
		this.testcaseid = testcaseid;
	}

	public Grouping getGrouping() {
		return this.grouping;
	}

	public void setGrouping(Grouping grouping) {
		this.grouping = grouping;
	}

	public String getTestcasename() {
		return this.testcasename;
	}

	public void setTestcasename(String testcasename) {
		this.testcasename = testcasename;
	}

	public String getTestcasedescription() {
		return this.testcasedescription;
	}

	public void setTestcasedescription(String testcasedescription) {
		this.testcasedescription = testcasedescription;
	}

	public int getTfsid() {
		return this.tfsid;
	}

	public void setTfsid(int tfsid) {
		this.tfsid = tfsid;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Set getTestcaseresultses() {
		return this.testcaseresultses;
	}

	public void setTestcaseresultses(Set testcaseresultses) {
		this.testcaseresultses = testcaseresultses;
	}

}
