package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Testcaseresults generated by hbm2java
 */
public class Testcaseresults implements java.io.Serializable {

	private Integer testcaseresultsid;
	private Testcase testcase;
	private Selwowscheduler selwowscheduler;
	private Date starttime;
	private Date endtime;
	private String results;
	private Integer passed;
	private String errors;

	public Testcaseresults() {
	}

	public Testcaseresults(Testcase testcase, Selwowscheduler selwowscheduler,
			Date starttime) {
		this.testcase = testcase;
		this.selwowscheduler = selwowscheduler;
		this.starttime = starttime;
	}

	public Testcaseresults(Testcase testcase, Selwowscheduler selwowscheduler,
			Date starttime, Date endtime, String results, Integer passed,
			String errors) {
		this.testcase = testcase;
		this.selwowscheduler = selwowscheduler;
		this.starttime = starttime;
		this.endtime = endtime;
		this.results = results;
		this.passed = passed;
		this.errors = errors;
	}

	public Integer getTestcaseresultsid() {
		return this.testcaseresultsid;
	}

	public void setTestcaseresultsid(Integer testcaseresultsid) {
		this.testcaseresultsid = testcaseresultsid;
	}

	public Testcase getTestcase() {
		return this.testcase;
	}

	public void setTestcase(Testcase testcase) {
		this.testcase = testcase;
	}

	public Selwowscheduler getSelwowscheduler() {
		return this.selwowscheduler;
	}

	public void setSelwowscheduler(Selwowscheduler selwowscheduler) {
		this.selwowscheduler = selwowscheduler;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getResults() {
		return this.results;
	}

	public void setResults(String results) {
		this.results = results;
	}

	public Integer getPassed() {
		return this.passed;
	}

	public void setPassed(Integer passed) {
		this.passed = passed;
	}

	public String getErrors() {
		return this.errors;
	}

	public void setErrors(String errors) {
		this.errors = errors;
	}

}
