package mappedTables;

// Generated Aug 31, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * Xmlfilepath generated by hbm2java
 */
public class Xmlfilepath implements java.io.Serializable {

	private Integer xmlfilepathid;
	private Server server;
	private String xmlfilepath;

	public Xmlfilepath() {
	}

	public Xmlfilepath(Server server, String xmlfilepath) {
		this.server = server;
		this.xmlfilepath = xmlfilepath;
	}

	public Integer getXmlfilepathid() {
		return this.xmlfilepathid;
	}

	public void setXmlfilepathid(Integer xmlfilepathid) {
		this.xmlfilepathid = xmlfilepathid;
	}

	public Server getServer() {
		return this.server;
	}

	public void setServer(Server server) {
		this.server = server;
	}

	public String getXmlfilepath() {
		return this.xmlfilepath;
	}

	public void setXmlfilepath(String xmlfilepath) {
		this.xmlfilepath = xmlfilepath;
	}

}
